name: Build Test APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 已是最新版，无需修改 ✅
      - uses: actions/checkout@v4
      
      # Java安装升级为v4 ✅
      - name: Set up JDK
        uses: actions/setup-java@v4  # 关键修复1：v3 → v4
        with: 
          java-version: '11'
          distribution: 'temurin'  # 推荐使用Eclipse Temurin
      
      - name: Build APK
        run: ./gradlew assembleRelease
        
      # 核心修复：上传组件升级 ✅
      - name: Upload APK
        uses: actions/upload-artifact@v4  # 关键修复2：v3 → v4
        with: 
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
